version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    container_name: backend
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env